# This file was generated by GoReleaser. DO NOT EDIT.
cask "typstpad" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "8175e9eececd141659022bb943b1e57f6c76c5e3b8f709804c0a91929cd03169"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "229b838eb77b24d7e81019afe08d838c8d27bae59eb77944227d3f414f4d65e2"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "819d4cd44094432cf23e3b199d71386465858ddd77e635466e65ebec950f40e6"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f92d25186321589d0e79ab0f674eaaa0390c1dad33cdccc81d89237086fce05"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_linux_arm64.tar.gz"
    end
  end

  name "typstpad"
  desc "CLI + MCP client for TypstPad, the self-hosted collaborative Typst editor"
  homepage "https://github.com/ladderlogix/typstpad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "typstpad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/typstpad"]
    end
  end

  # No zap stanza required

end
