# This file was generated by GoReleaser. DO NOT EDIT.
cask "typstpad" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "71cd8d8567ebaefe6279f05d52769b6d86d722ef3f1f91376b16974ce50f6a23"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6694058ecbaf38bb0a0aa6a0d96e8cef65384118899cb3356d12593cd358d7f8"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f93f2969bc8dd5e05723fe0d7b3012d15966b6464b10a931131d7b88af37a497"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "479a6e8a9be1b42b8622040acf7b9f1655e3a3c936c7498deb8594f0324af2c3"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_linux_arm64.tar.gz"
    end
  end

  name "typstpad"
  desc "CLI + MCP client for TypstPad, the self-hosted collaborative Typst editor"
  homepage "https://github.com/ladderlogix/typstpad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "typstpad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/typstpad"]
    end
  end

  # No zap stanza required

end
