# This file was generated by GoReleaser. DO NOT EDIT.
cask "typstpad" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "95f39a92cdb62d4c3521f2e20c35acba98ec24c11b69cf3834a1f8bb02985256"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dccf993ff28b9b5b25b3a1f58e61296735b5b0abd53dfde38da60f25805ce6cc"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "232dc22636fac961fe57fe1bfb7eb1ebef8efa9ca14067c70165b72958cdf59a"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0524a6734f466684f6a564cd5566d13a7e37db8e1c82ab829a0c1c6e6292a3db"
      url "https://github.com/ladderlogix/typstpad/releases/download/v#{version}/typstpad_#{version}_linux_arm64.tar.gz"
    end
  end

  name "typstpad"
  desc "CLI + MCP client for TypstPad, the self-hosted collaborative Typst editor"
  homepage "https://github.com/ladderlogix/typstpad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "typstpad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/typstpad"]
    end
  end

  # No zap stanza required

end
